apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-component-craaaa
  description: faa
  annotations:
    github.com/project-slug: shmidt-i-test/another-test-02425636hhhhh
spec:
  type: website
  lifecycle: experimental
  owner: shmidt-i
